//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by OCS_DEPLOY_TOOL.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDD_OCS_DEPLOY_TOOL_DIALOG      102
#define IDR_MAINFRAME                   128
#define IDD_CREDENTIALS_DIALOG          131
#define IDD_WIN_AGENT_SETUP_DIALOG      133
#define IDD_DEPLOYING_DIALOG            134
#define IDD_UNIX_AGENT_SETUP_DIALOG     135
#define IDD_SELECT_HOSTS_DIALOG         136
#define IDD_HOST_ADDRESS_DIALOG         137
#define IDD_TOOLS_DIALOG                138
#define IDC_STATUS                      200
#define IDC_EDIT_PASSWORD               201
#define IDC_EDIT_LOGIN                  202
#define IDC_BUTTON_WIN_DEPLOY           203
#define IDC_BUTTON_UNIX_DEPLOY          204
#define IDC_RADIO_IP                    205
#define IDC_RADIO_LIST                  206
#define IDC_IPADDRESS_FROM              207
#define IDC_IPADDRESS_TO                208
#define IDC_LIST_COMPUTERS              209
#define IDC_BUTTON_ADD                  210
#define IDC_BUTTON_REMOVE               211
#define IDC_EDIT_EXE                    212
#define IDC_BUTTON_IMPORT               212
#define IDC_BUTTON_EXE                  213
#define IDC_EDIT_SERVER_IP              214
#define IDC_CHECK_DEBUG                 215
#define IDC_CHECK_LAUNCH_INVENTORY      216
#define IDC_EDIT_SERVER_PORT            217
#define IDC_CHECK_NO_SERVICE            217
#define IDC_CHECK_NO_PROXY              218
#define IDC_CHECK_DEBUG3                218
#define IDC_CHECK_NO_SYSTRAY            218
#define IDC_EDIT_OPTIONS                219
#define IDC_LIST_FILES                  220
#define IDC_WEB_OCS                     220
#define IDC_EDIT_INSTALL                221
#define IDC_WEB_PSEXEC                  221
#define IDC_WEB_PUTTY                   222
#define IDC_MAX_THREADS                 223
#define IDC_STOP_THREADS                224
#define IDC_SLIDER_THREADS              225
#define IDC_STATUS_THREADS              226
#define IDC_MESSAGE_HANDLER_LISTBOX     227
#define IDC_MESSAGE_HANDLER_STATUS      228
#define IDC_MESSAGE_GET_MAX_THREADS     229
#define IDC_BUTTON_CHANGE_DIRECTORY     230
#define IDC_BUTTON_SAVE_LOG             231
#define IDC_CHECK_ETC_DIRECTORY         232
#define IDC_EDIT_TAG_VALUE              233
#define IDC_EDIT_HELP_MESSAGE           234
#define IDC_EDIT_SSH_KEY                235
#define IDC_COMBO_ETC_DIRECTORY         236
#define IDC_BUTTON_OPTION               237
#define IDC_EDIT_PSEXEC                 238
#define IDC_BUTTON_PSEXEC               239
#define IDC_EDIT_PUTTY                  240
#define IDC_BUTTON_PUTTY                241
#define IDC_EDIT_PSCP                   242
#define IDC_BUTTON_PSCP                 243
#define IDC_WEB_PSCP                    244
#define IDS_ABOUTBOX                    400
#define IDS_OCS_DEPLOY_TOOL             401
#define IDS_SELECT_REMOTE_HOST          402
#define IDS_SELECT_AGENT_FILE           403
#define IDS_SELECT_OTHER_FILE           404
#define IDS_SELECT_IPDISCOVER_FILE      405
#define IDS_SELECT_CSV_FILE             406
#define IDS_SELECT_LOG_FILE             407
#define IDS_SELECT_PUTTY_KEY            408
#define IDS_SELECT_PSEXEC_FILE          409
#define IDS_SELECT_PUTTY_FILE           410
#define IDS_SELECT_PSCP_FILE            411
#define IDS_STATUS_TESTING_REMOTE_HOST  450
#define IDS_STATUS_CONNECTING_REMOTE_HOST 451
#define IDS_STATUS_DISCONNECTING_REMOTE_HOST 452
#define IDS_STATUS_DEPLOYMENT_FINISHED  453
#define IDS_STATUS_CREATING_DIRECTORY   454
#define IDS_STATUS_COPYING_FILES        455
#define IDS_STATUS_LAUNCHING_SETUP      456
#define IDS_STATUS_LAUNCHING_INVENTORY  457
#define IDS_STATUS_SETUP_KILLED         458
#define IDS_STATUS_AGENT_SETUP_SUCCESS  459
#define IDS_STATUS_LOG_FILE             460
#define IDS_STATUS_DISPLAYING_LOG       461
#define IDS_STATUS_EXPORT_FAILED_HOSTS  462
#define IDS_STATUS_START_DEPLOYMENT     463
#define IDS_STATUS_RUNNING_DEPLOYMENT   464
#define IDS_STATUS_STOP_DEPLOYMENT      465
#define IDS_STATUS_RETREIVING_PROGRAM_FILES_REGISTRY 467
#define IDS_STATUS_RETREIVING_PROGRAM_FILES_REMCOM 468
#define IDS_STATUS_HELP_WIN_CREDENTIALS 469
#define IDS_STATUS_HELP_UNIX_CREDENTIALS 470
#define IDS_STATUS_CLEANING_TEMP_DIR    471
#define IDS_STATUS_SHOW_USED_DIRECTORY	472
#define IDS_STATUS_RETREIVING_PROGRAM_DATA_REMCOM 473
#define IDS_ERROR_TESTING_REMOTE_HOST   500
#define IDS_ERROR_CONNECTING_REMOTE_HOST 501
#define IDS_ERROR_REMOTE_REGISTRY_ACCESS 502
#define IDS_ERROR_RETREIVING_REMOTE_PROGRAM_FILES 503
#define IDS_ERROR_CREATING_DIRECTORY    504
#define IDS_ERROR_COPYING_FILES         505
#define IDS_ERROR_LAUNCHING_SETUP       506
#define IDS_ERROR_LOG_NOT_FOUND         507
#define IDS_ERROR_AGENT_SETUP_FAILURE   508
#define IDS_ERROR_OPENING_FILE          509
#define IDS_ERROR_GET_FOLDER            510
#define IDS_ERROR_INVALID_VALUE         511
#define IDS_ERROR_HOST_NOT_FOUND        512
#define IDS_ERROR_DISPLAY_FOLDER        513
#define IDS_ERROR_CLEANING_TEMP_DIR     514

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         246
#define _APS_NEXT_SYMED_VALUE           514
#endif
#endif
